version: '2'
services:
    php:
        build: php-fpm
        ports:
            - '9000:9000'
        volumes:
            - ../symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
    nginx:
        build: nginx
        ports:
            - '80:80'
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached